config/routes.rb
Nups::Application.routes.draw do
  mount Resque::Server.new => "/resque"

  # first created -> highest priority.
  root :to => "frame#index"

  devise_for :users

  match 'newsletters' => 'newsletters#index', :as => :all_newsletters
  match 'newsletters/stats' => 'newsletters#stats', :as => :all_newsletter_stats

  namespace :admin do
    resources :users
    resources :accounts
  end

  namespace :public do
    resources :recipients, :only => [:index, :show, :destroy]
  end

  # resource route with sub-resources:
  resources :accounts, :only => [:index] do
    resources :newsletters do
      member do
        get :start
        get :stop
      end
    end

    resources :recipients do
      collection do
        get :delete
        delete :multiple_destroy
      end

      resources :send_outs
    end

    resources :assets, :only => :create
    resources :charts, :only => :index
  end

  match 'subscribe/:account_permalink'        => 'public/recipients#create',           :via => 'post',  :as => :subscribe
  match 'confirm/:recipient_confirm_code'     => 'public/recipients#confirm',          :via => 'get',   :as => :confirm #put
  match 'unsubscribe/:recipient_confirm_code' => 'public/recipients#destroy_confirm',  :via => 'get',   :as => :unsubscribe
  match 'unsubscribe/:recipient_confirm_code' => 'public/recipients#destroy',          :via => 'delete'
  match 'remove/:account_permalink'           => 'public/recipients#destroy_by_email', :via => 'delete'

  match ':recipient_id/:send_out_id(/:image)' => 'public/newsletters#show',            :via => 'get',   :as => :newsletter
end
#== Route Map
# Generated on 10 Jan 2012 19:05
#
#                                root        /                                                                           frame#index
#                    new_user_session GET    /users/sign_in(.:format)                                                    devise/sessions#new
#                        user_session POST   /users/sign_in(.:format)                                                    devise/sessions#create
#                destroy_user_session GET    /users/sign_out(.:format)                                                   devise/sessions#destroy
#                       user_password POST   /users/password(.:format)                                                   devise/passwords#create
#                   new_user_password GET    /users/password/new(.:format)                                               devise/passwords#new
#                  edit_user_password GET    /users/password/edit(.:format)                                              devise/passwords#edit
#                                     PUT    /users/password(.:format)                                                   devise/passwords#update
#            cancel_user_registration GET    /users/cancel(.:format)                                                     devise/registrations#cancel
#                   user_registration POST   /users(.:format)                                                            devise/registrations#create
#               new_user_registration GET    /users/sign_up(.:format)                                                    devise/registrations#new
#              edit_user_registration GET    /users/edit(.:format)                                                       devise/registrations#edit
#                                     PUT    /users(.:format)                                                            devise/registrations#update
#                                     DELETE /users(.:format)                                                            devise/registrations#destroy
#                     all_newsletters        /newsletters(.:format)                                                      newsletters#index
#                all_newsletter_stats        /newsletters/stats(.:format)                                                newsletters#stats
#                         admin_users GET    /admin/users(.:format)                                                      admin/users#index
#                                     POST   /admin/users(.:format)                                                      admin/users#create
#                      new_admin_user GET    /admin/users/new(.:format)                                                  admin/users#new
#                     edit_admin_user GET    /admin/users/:id/edit(.:format)                                             admin/users#edit
#                          admin_user GET    /admin/users/:id(.:format)                                                  admin/users#show
#                                     PUT    /admin/users/:id(.:format)                                                  admin/users#update
#                                     DELETE /admin/users/:id(.:format)                                                  admin/users#destroy
#                      admin_accounts GET    /admin/accounts(.:format)                                                   admin/accounts#index
#                                     POST   /admin/accounts(.:format)                                                   admin/accounts#create
#                   new_admin_account GET    /admin/accounts/new(.:format)                                               admin/accounts#new
#                  edit_admin_account GET    /admin/accounts/:id/edit(.:format)                                          admin/accounts#edit
#                       admin_account GET    /admin/accounts/:id(.:format)                                               admin/accounts#show
#                                     PUT    /admin/accounts/:id(.:format)                                               admin/accounts#update
#                                     DELETE /admin/accounts/:id(.:format)                                               admin/accounts#destroy
#                   public_recipients GET    /public/recipients(.:format)                                                public/recipients#index
#                    public_recipient GET    /public/recipients/:id(.:format)                                            public/recipients#show
#                                     DELETE /public/recipients/:id(.:format)                                            public/recipients#destroy
#            start_account_newsletter GET    /accounts/:account_id/newsletters/:id/start(.:format)                       newsletters#start
#             stop_account_newsletter GET    /accounts/:account_id/newsletters/:id/stop(.:format)                        newsletters#stop
#                 account_newsletters GET    /accounts/:account_id/newsletters(.:format)                                 newsletters#index
#                                     POST   /accounts/:account_id/newsletters(.:format)                                 newsletters#create
#              new_account_newsletter GET    /accounts/:account_id/newsletters/new(.:format)                             newsletters#new
#             edit_account_newsletter GET    /accounts/:account_id/newsletters/:id/edit(.:format)                        newsletters#edit
#                  account_newsletter GET    /accounts/:account_id/newsletters/:id(.:format)                             newsletters#show
#                                     PUT    /accounts/:account_id/newsletters/:id(.:format)                             newsletters#update
#                                     DELETE /accounts/:account_id/newsletters/:id(.:format)                             newsletters#destroy
#           delete_account_recipients GET    /accounts/:account_id/recipients/delete(.:format)                           recipients#delete
# multiple_destroy_account_recipients DELETE /accounts/:account_id/recipients/multiple_destroy(.:format)                 recipients#multiple_destroy
#         account_recipient_send_outs GET    /accounts/:account_id/recipients/:recipient_id/send_outs(.:format)          send_outs#index
#                                     POST   /accounts/:account_id/recipients/:recipient_id/send_outs(.:format)          send_outs#create
#      new_account_recipient_send_out GET    /accounts/:account_id/recipients/:recipient_id/send_outs/new(.:format)      send_outs#new
#     edit_account_recipient_send_out GET    /accounts/:account_id/recipients/:recipient_id/send_outs/:id/edit(.:format) send_outs#edit
#          account_recipient_send_out GET    /accounts/:account_id/recipients/:recipient_id/send_outs/:id(.:format)      send_outs#show
#                                     PUT    /accounts/:account_id/recipients/:recipient_id/send_outs/:id(.:format)      send_outs#update
#                                     DELETE /accounts/:account_id/recipients/:recipient_id/send_outs/:id(.:format)      send_outs#destroy
#                  account_recipients GET    /accounts/:account_id/recipients(.:format)                                  recipients#index
#                                     POST   /accounts/:account_id/recipients(.:format)                                  recipients#create
#               new_account_recipient GET    /accounts/:account_id/recipients/new(.:format)                              recipients#new
#              edit_account_recipient GET    /accounts/:account_id/recipients/:id/edit(.:format)                         recipients#edit
#                   account_recipient GET    /accounts/:account_id/recipients/:id(.:format)                              recipients#show
#                                     PUT    /accounts/:account_id/recipients/:id(.:format)                              recipients#update
#                                     DELETE /accounts/:account_id/recipients/:id(.:format)                              recipients#destroy
#                      account_assets POST   /accounts/:account_id/assets(.:format)                                      assets#create

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationNupsController
  before_filter :load_account, :if => lambda { params[:account_id] }

  respond_to :html

  def index
    @user        = User.find(params[:user_id]) if params[:user_id] && current_user.admin?
    @user      ||= (@account) ? @account.user : current_user
    @accounts    = @user.accounts

    @newsletters = @user.newsletters.with_account(@account).
                         order('IFNULL(deliver_at, IFNULL(delivery_started_at,newsletters.updated_at)) DESC').
                         page(params[:page]).per(15)
    if request.xhr?
      render :partial => 'newsletters'
    end
  end

  def stats
    @newsletters = current_user.admin? ? Newsletter : current_user.newsletters
    @newsletters = @newsletters.find_all_by_id(params[:ids])
    @newsletters.map(&:update_stats!)
    render :json => @newsletters.to_json(
      :except => [:subject, :content, :account_id, :last_sent_id, :mode, :status],
      :methods => [:progress_percent, :sending_time, :finishs_count, :sendings_per_second]
    )
  end

  def show
    @newsletter = @account.newsletters.find(params[:id])

    recipient = Recipient.new(:email => current_user.email)
    @newsletter_issue = NewsletterMailer.issue(@newsletter, recipient)
    render :text => @newsletter_issue.html_part.body.decoded, :layout => false
  end

  def new
    render_404 && return unless @account

    draft = @account.newsletters.find_by_id(params[:draft_id])
    @newsletter = @account.newsletters.new(:draft => draft)
    @newsletter.subject ||= @account.subject

    respond_with @newsletter
  end

  def edit
    @newsletter = @account.newsletters.find(params[:id])
    render :new
  end

  def create
    # fix to make attachment_id not break
    params[:newsletter] = {:account => @account}.merge(params[:newsletter]) if params[:newsletter]

    @newsletter = @account.newsletters.new(params[:newsletter])

    if @newsletter.save
      redirect_to( account_newsletters_path(@account), :notice => 'Newsletter was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    @newsletter = @account.newsletters.find(params[:id])

    if @newsletter.update_attributes(params[:newsletter])
      redirect_to( account_newsletters_path(@account), :notice => 'Newsletter was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @newsletter = @account.newsletters.find(params[:id])
    @newsletter.destroy

    if request.xhr?
      render :json => @newsletter.to_json(:only => [:id])
    else
      redirect_to account_newsletters_path(@account)
    end
  end

  ########################################################

  def start
    @newsletter = @account.newsletters.find(params[:id])

    if params[:mode] == 'live'
      @newsletter.send_live!
    else
      @newsletter.send_test! [current_user.email, $mail_config['test_recipient_emails']].compact.join(',')
    end

    if request.xhr?
      render :json => @newsletter.reload.to_json(
        :except => [:subject, :content, :account_id, :last_sent_id, :mode, :status],
        :methods => [:progress_percent, :sending_time, :finishs_count, :sendings_per_second]
      )
    else
      redirect_to account_newsletters_path(@account)
    end
  end

  def stop
    @newsletter = @account.newsletters.find(params[:id])
    @newsletter.stop!

    if request.xhr?
      render :json => @newsletter.reload.to_json(
        :except => [:subject, :content, :account_id, :last_sent_id, :mode, :status],
        :methods => [:progress_percent, :sending_time, :finishs_count, :sendings_per_second]
      )
    else
      redirect_to account_newsletters_path(@account)
    end
  end

end

app/helpers/newsletters_helper.rb
module NewslettersHelper

  def pull_time
    Rails.env.test? ? 250 : 2000
  end
end

app/views/newsletters/_form.html.haml
- if @newsletter.errors.any?
  %tr
    %td{:colspan => 2, :align => 'center'}
      #errorExplanation
        #{pluralize(@newsletter.errors.count, "error")} prohibited this newsletter from being saved:
      %ul
        - @newsletter.errors.full_messages.each do |msg|
          %li= msg


%tr
  %th= Newsletter.human_attribute_name(:from) + ':'
  %td= @account.from


%tr
  %th= Newsletter.human_attribute_name(:subject) + ':'
  %td= form.text_field :subject, :size => 60


- if @account.has_scheduling
  %tr
    %th= Newsletter.human_attribute_name(:deliver_at) + ':'
    %td= form.datetime_select :deliver_at, :order => [:day, :month, :year], :start_year => Date.current.year, :end_year => Date.current.year + 3


- if @account.has_attachments
  %tr
    %th{:valign => "top"}= Newsletter.human_attribute_name(:attachments) + ':'
    %td
      %input{:type => "hidden", :name => "newsletter[attachment_ids][]"}
      = render 'plupload'

      #upcontainer
        %input#pickfiles{:type => "button", :disabled => true, :value => t('newsletters.ctrl.add_files')}
        #filelist
          = render @newsletter.attachments
        #uploadlist

app/views/newsletters/_newsletter.html.erb
<tr id="status_<%= newsletter.id %>" class="<%= cycle('bgdark', 'bglight') %>">
  <td>
    <% if newsletter.created? %>
      <%= link_to t('newsletters.ctrl.send_test'), start_account_newsletter_path(*newsletter.route) %>
    <% elsif newsletter.scheduled? %>
      <%= image_tag( 'spinner.gif', :id => "spinner#{newsletter.id}" )  %>
    <% else %>
      <div style="width:100px; border: 1px solid #000; overflow: hidden;margin:0 auto;padding:0;">
       <div style='background-color: <%= ( newsletter.errors_count && newsletter.errors_count > 0 ) ? 'red' : 'green' %>; width: <%= newsletter.progress_percent %>px; color: white;' align='center'>
         <%= newsletter.progress_percent %>%
       </div>
      </div>
      <%= l Time.at(newsletter.sending_time), :format => :time %> - <%= "%.1f" % newsletter.deliveries_per_second %>/sec.
    <% end %>
  </td>
  <td><%= newsletter.human_status %> <%= newsletter.human_mode %></td>
  <td align="left"> <%# style="background-color:<%= newsletter.color % >"  %>
    <strong><%= l (newsletter.deliver_at || newsletter.updated_at), :format => :nl %></strong>:
    <%= link_to truncate(newsletter.subject, :length => 40), account_newsletter_path(*newsletter.route) %></td>
  </td>
  <td><%= newsletter.recipients_count %></td>
  <td>
  <% if newsletter.running? || newsletter.scheduled? %>
    <%= link_to( t('newsletters.ctrl.pause'), stop_account_newsletter_path(*newsletter.route), :confirm => t('newsletters.confirm.pause')) %>
    <%= delayed_remote_function( :url => account_newsletter_path(*newsletter.route), :method => :get, :delay => 3000, :replace => "#status_#{newsletter.id}" ) %>
  <% else %> <!-- Default Menu -->
     <%= link_to  t('ctrl.preview'), newsletter.route %> &bull;
     <%= link_to  t('ctrl.edit'), edit_account_newsletter_path(*newsletter.route) %> &bull;
     <%#= link_to 'Delete', newsletter.route, :method => 'delete', :confirm => "Really delete newsletter?" %>
     <%= link_to( t('newsletters.ctrl.send_test'), start_account_newsletter_path(*newsletter.route)) unless newsletter.finished_live? %>
     <%= link_to( t('newsletters.ctrl.send_live'), start_account_newsletter_path(*newsletter.route, :mode => 'live'), :confirm => t('newsletters.confirm.start') ) if newsletter.finished_test? %>
     <%= link_to( t('newsletters.ctrl.resume'), start_account_newsletter_path(*newsletter.route, :mode => (newsletter.live? ? 'live' : nil) ), :confirm => t('newsletters.confirm.resume') ) if newsletter.stopped? %>
  <% end %>
  </td>
</tr>

app/views/newsletters/_newsletter.html.haml
%tr{ :id => "newsletter-#{newsletter.id}", :class => "newsletter #{newsletter.state}", :"data-newsletter-path" => all_newsletter_stats_path, :"data-pull-time" => pull_time }
  %td.icon
    %a.preview{ :href => account_newsletter_path(*newsletter.route), :rel => "#overlay" }
      %span= newsletter.state

  %td.info
    %strong= l(newsletter.deliver_at || newsletter.delivery_started_at || newsletter.updated_at, :format => :nl) + ':'
    = link_to newsletter.subject, account_newsletter_path(*newsletter.route), :rel => "#overlay"

    .progress-bar
      .progress{:style => "width: #{newsletter.progress_percent}%"}
        %label= newsletter.progress_percent.to_s + '%'

    .stats
      .progress-percent
        #{newsletter.progress_percent}%
      .sending-time
        = distance_of_time(newsletter.delivery_started_at || Time.now, newsletter.delivery_ended_at || Time.now, true)
      .sendings-per-sec
        #{newsletter.sendings_per_second}/sec.
      .reads
        Read:
        %span= newsletter.reads_count
      .finishs
        Unread:
        %span= newsletter.finishs_count
      .bounces
        Bounced:
        %span= newsletter.bounces_count
      .fails
        Failed:
        %span= newsletter.fails_count
  %td.recipients
    = newsletter.recipients_count

  %td.actions
    %a.button.send-test{ :href => start_account_newsletter_path(*newsletter.route), 'data-remote' => 'true' }
      %span=t('newsletters.ctrl.send_test')
    %a.button.send-live{ :href => start_account_newsletter_path(*newsletter.route, :mode => 'live'), 'data-remote' => 'true', 'data-confirm' => t('newsletters.confirm.send_live') }
      %span=t('newsletters.ctrl.send_live')
    %a.button.resume{ :href => start_account_newsletter_path(*newsletter.route, :mode => 'live'), 'data-remote' => 'true', 'data-confirm' => t('newsletters.confirm.resume') }
      %span=t('newsletters.ctrl.resume')
    %a.button.stop{ :href => stop_account_newsletter_path(*newsletter.route), 'data-remote' => 'true', 'data-confirm' => t('newsletters.confirm.stop') }
      %span=t('newsletters.ctrl.stop')
    %a.button.clone{ :href => new_account_newsletter_path(newsletter.account, :draft_id => newsletter.id) }
      %span=t('newsletters.ctrl.clone')

  %td.menu
    %a.icon.preview{ :href => account_newsletter_path(*newsletter.route), :rel => "#overlay" }
      %span=t('ctrl.preview')
    %a.icon.edit{ :href => edit_account_newsletter_path(*newsletter.route) }
      %span=t('ctrl.edit')
    %a.icon.delete{ :href => account_newsletter_path(*newsletter.route), 'data-method' => 'delete', 'data-confirm' => t('newsletters.confirm.delete'), 'data-remote' => 'true' }
      %span=t('ctrl.delete')

app/views/newsletters/_newsletters.html.haml
- if @newsletters.count > 0
  = render @newsletters
  %tr.paginate
    %td{colspan:5, align:"center"}
      = paginate @newsletters, :remote => true

app/views/newsletters/_plupload.html.erb
<script type="text/javascript">
<%#= javascript_tag do %>
  var re = null;
  
 $(function(){
  var uploader = new plupload.Uploader({
   runtimes: "gears,flash,html5,silverlight",
   browse_button: 'pickfiles',
   container: "upcontainer",
   max_file_size: '3mb',
   url: '<%= account_assets_path(@account) %>',
   flash_swf_url: "<%= asset_path('plupload/plupload.flash.swf') %>",
   silverlight_xap_url: "<%= asset_path('plupload/plupload.silverlight.xap') %>",
   multipart: true,
   multipart_params: {
    "authenticity_token": '<%= form_authenticity_token %>',
    "newsletter_id": '<%= @newsletter.try(:id) %>'
   }
  });

  uploader.bind('Init', function(up, params) {
       $('#runtime').html(params.runtime);
       $('#pickfiles').attr('disabled', false);
  });
  
  uploader.bind('QueueChanged', function() {
      uploader.start();
  });

  uploader.bind('FilesAdded', function(up, files) {
    $.each(files, function(i, file) {
           $('#uploadlist').append(
            '<div id="file_' + file.id + '" class="upload">' +
              '<%= image_tag( 'spinner.gif', :valign => :middle) %> ' +
              '<b><%= t('newsletters.uploading') %>:</b> ' +
                file.name + ' (' + plupload.formatSize(file.size) + ') ' +
              '<b>0%</b>' +
            '</div>'
            );
       });
   });

   uploader.bind('Error', function(up, e) {
     alert('error' + e.message)
     $('#uploadlist').html('')
   });

   uploader.bind('UploadProgress', function(up, file) {
      $('#file_' + file.id + " b").html(file.percent + "%");
   });

   uploader.bind('FileUploaded', function(up, file, response) {
      $('#filelist').append(response.response);
      $('#file_' + file.id).remove();
   });

   uploader.init();
 });
</script>

app/views/newsletters/index.html.haml
#newsletters.index
  %h2= t('newsletters.title')

  - path = @account ? new_account_newsletter_path(@account) : "#"
  - style = @account ? "" : "display: none;"
  %a.button.new{href:path, style:style}
    %span= t('newsletters.new')

  %ul.tabs
    %li
      - klass = @account ? nil : 'current'
      = link_to t('newsletters.all'), all_newsletters_path, :class => klass
    - @accounts.each do |account|
      %li
        - klass = (@account == account) ? 'current' : nil
        = link_to account.name, account_newsletters_path(account), :class => klass, :"data-new-url" => new_account_newsletter_path(account)

  %table.content.zebra
    %thead
      %tr
        %th{width:44}
        %th{}= Newsletter.human_attribute_name(:progress)
        %th{width:120}= Newsletter.human_attribute_name(:recipients_count)
        %th{width:120}= t('newsletters.action')
        %th{width:120}= t('newsletters.menu')

    %tbody
      =  render :partial => 'newsletters'

    %tfoot
      %tr
        %td{colspan:5}
          = t('newsletters.nothing')

app/views/newsletters/new.html.haml
#newsletters.form
  = form_for [@newsletter.account, @newsletter]  do |form|
    %table.content{:style => "width: 700px"}
      %thead
        %tr
          %th{:align => 'center'}
            %h2= @newsletter.account.name

      %tbody
        %tr
          %td.form{:align => 'center'}
            %table{:colpadding => 0, :collspacing => 0, :width => 600}
              = render 'form', :form => form

        %tr
          %td.text{:align => 'center'}
            = form.text_area :content, :class => "cleditor", :rows => 80 #, :required => "required"

        %tr
          %td{:align => 'center'}
            = form.submit t('ctrl.save')

app/views/newsletters/show.html.erb
<div id="newsletter">
  <table border="0" id="formular" width="700">
    <thead>    
      <tr><td colspan="2" align="center"><h2><%= t 'newsletters.form.title' %></h2> - ID: <%= @newsletter.id %><br>
        <%= t 'newsletters.form.current_time' %>: <%= l Time.now, :format => :nl %>
      </td></tr>      
    </thead>
    <tbody>
      <tr><th><%= Newsletter.human_attribute_name(:from) %>:</th><td><%=  @newsletter.from  %></td></tr>
      <tr><th><%= Newsletter.human_attribute_name(:deliver_at) %>:</th><td><%= l (@newsletter.deliver_at || @newsletter.updated_at), :format => :nl %></td></tr>
      <tr><th><%= Newsletter.human_attribute_name(:subject) %>:</th><td><%= @newsletter.subject %></td></tr>
      <% if @account.has_attachments %>
        <tr>
          <th valign="top"><%= Newsletter.human_attribute_name(:attachments) %>:</th>
          <td>
            <div id="filelist">
                <%= render @newsletter.attachments, :no_checkbox => true %>
            </div>
          </td>
        </tr>
      <% end %>      
      <tr><th><%= Newsletter.human_attribute_name(:status) %>:</th><td><%= @newsletter.human_status %> <%= @newsletter.human_mode %></td></tr>
      <tr><td colspan="2" align="center">
          <%= link_to t('ctrl.edit'), edit_account_newsletter_path(*@newsletter.route) %> &bull;
          <%= link_to t('ctrl.delete'), @newsletter.route, :method => 'delete', :confirm => t('ctrl.confirm') %> &bull;
          <%= link_to( t('newsletters.ctrl.send_test'), start_account_newsletter_path(*@newsletter.route)) unless @newsletter.finished_live? %>
       </td></tr>
    </tbody>
  </table>
  <br>
  <table border="0" id="formular" width="700">
      <%# TODO: auto expand, HTML editor???  %>
      <tr><td align="center">
      <iframe src="<%= preview_account_newsletter_path(*@newsletter.route, :example_user => params[:example_user] ) %>" width="680" height="600"></iframe>
      </td></tr>
      <tr><td colspan="2" align="center">
        <%= link_to t('ctrl.back'), newsletters_path %> |
        <%= link_to t('ctrl.edit'), edit_account_newsletter_path(*@newsletter.route) %>
       </td></tr>        
  </table>
</div>