config/routes.rb
Nups::Application.routes.draw do
  mount Resque::Server.new => "/resque"

  # first created -> highest priority.
  root :to => "frame#index"

  devise_for :users

  match 'newsletters' => 'newsletters#index', :as => :all_newsletters
  match 'newsletters/stats' => 'newsletters#stats', :as => :all_newsletter_stats

  namespace :admin do
    resources :users
    resources :accounts
  end

  namespace :public do
    resources :recipients, :only => [:index, :show, :destroy]
  end

  # resource route with sub-resources:
  resources :accounts, :only => [:index] do
    resources :newsletters do
      member do
        get :start
        get :stop
      end
    end

    resources :recipients do
      collection do
        get :delete
        delete :multiple_destroy
      end

      resources :send_outs
    end

    resources :assets, :only => :create
    resources :charts, :only => :index
  end

  match 'subscribe/:account_permalink'        => 'public/recipients#create',           :via => 'post',  :as => :subscribe
  match 'confirm/:recipient_confirm_code'     => 'public/recipients#confirm',          :via => 'get',   :as => :confirm #put
  match 'unsubscribe/:recipient_confirm_code' => 'public/recipients#destroy_confirm',  :via => 'get',   :as => :unsubscribe
  match 'unsubscribe/:recipient_confirm_code' => 'public/recipients#destroy',          :via => 'delete'
  match 'remove/:account_permalink'           => 'public/recipients#destroy_by_email', :via => 'delete'

  match ':recipient_id/:send_out_id(/:image)' => 'public/newsletters#show',            :via => 'get',   :as => :newsletter
end
#== Route Map
# Generated on 10 Jan 2012 19:05
#
#                                root        /                                                                           frame#index
#                    new_user_session GET    /users/sign_in(.:format)                                                    devise/sessions#new
#                        user_session POST   /users/sign_in(.:format)                                                    devise/sessions#create
#                destroy_user_session GET    /users/sign_out(.:format)                                                   devise/sessions#destroy
#                       user_password POST   /users/password(.:format)                                                   devise/passwords#create
#                   new_user_password GET    /users/password/new(.:format)                                               devise/passwords#new
#                  edit_user_password GET    /users/password/edit(.:format)                                              devise/passwords#edit
#                                     PUT    /users/password(.:format)                                                   devise/passwords#update
#            cancel_user_registration GET    /users/cancel(.:format)                                                     devise/registrations#cancel
#                   user_registration POST   /users(.:format)                                                            devise/registrations#create
#               new_user_registration GET    /users/sign_up(.:format)                                                    devise/registrations#new
#              edit_user_registration GET    /users/edit(.:format)                                                       devise/registrations#edit
#                                     PUT    /users(.:format)                                                            devise/registrations#update
#                                     DELETE /users(.:format)                                                            devise/registrations#destroy
#                     all_newsletters        /newsletters(.:format)                                                      newsletters#index
#                all_newsletter_stats        /newsletters/stats(.:format)                                                newsletters#stats
#                         admin_users GET    /admin/users(.:format)                                                      admin/users#index
#                                     POST   /admin/users(.:format)                                                      admin/users#create
#                      new_admin_user GET    /admin/users/new(.:format)                                                  admin/users#new
#                     edit_admin_user GET    /admin/users/:id/edit(.:format)                                             admin/users#edit
#                          admin_user GET    /admin/users/:id(.:format)                                                  admin/users#show
#                                     PUT    /admin/users/:id(.:format)                                                  admin/users#update
#                                     DELETE /admin/users/:id(.:format)                                                  admin/users#destroy
#                      admin_accounts GET    /admin/accounts(.:format)                                                   admin/accounts#index
#                                     POST   /admin/accounts(.:format)                                                   admin/accounts#create
#                   new_admin_account GET    /admin/accounts/new(.:format)                                               admin/accounts#new
#                  edit_admin_account GET    /admin/accounts/:id/edit(.:format)                                          admin/accounts#edit
#                       admin_account GET    /admin/accounts/:id(.:format)                                               admin/accounts#show
#                                     PUT    /admin/accounts/:id(.:format)                                               admin/accounts#update
#                                     DELETE /admin/accounts/:id(.:format)                                               admin/accounts#destroy
#                   public_recipients GET    /public/recipients(.:format)                                                public/recipients#index
#                    public_recipient GET    /public/recipients/:id(.:format)                                            public/recipients#show
#                                     DELETE /public/recipients/:id(.:format)                                            public/recipients#destroy
#            start_account_newsletter GET    /accounts/:account_id/newsletters/:id/start(.:format)                       newsletters#start
#             stop_account_newsletter GET    /accounts/:account_id/newsletters/:id/stop(.:format)                        newsletters#stop
#                 account_newsletters GET    /accounts/:account_id/newsletters(.:format)                                 newsletters#index
#                                     POST   /accounts/:account_id/newsletters(.:format)                                 newsletters#create
#              new_account_newsletter GET    /accounts/:account_id/newsletters/new(.:format)                             newsletters#new
#             edit_account_newsletter GET    /accounts/:account_id/newsletters/:id/edit(.:format)                        newsletters#edit
#                  account_newsletter GET    /accounts/:account_id/newsletters/:id(.:format)                             newsletters#show
#                                     PUT    /accounts/:account_id/newsletters/:id(.:format)                             newsletters#update
#                                     DELETE /accounts/:account_id/newsletters/:id(.:format)                             newsletters#destroy
#           delete_account_recipients GET    /accounts/:account_id/recipients/delete(.:format)                           recipients#delete
# multiple_destroy_account_recipients DELETE /accounts/:account_id/recipients/multiple_destroy(.:format)                 recipients#multiple_destroy
#         account_recipient_send_outs GET    /accounts/:account_id/recipients/:recipient_id/send_outs(.:format)          send_outs#index
#                                     POST   /accounts/:account_id/recipients/:recipient_id/send_outs(.:format)          send_outs#create
#      new_account_recipient_send_out GET    /accounts/:account_id/recipients/:recipient_id/send_outs/new(.:format)      send_outs#new
#     edit_account_recipient_send_out GET    /accounts/:account_id/recipients/:recipient_id/send_outs/:id/edit(.:format) send_outs#edit
#          account_recipient_send_out GET    /accounts/:account_id/recipients/:recipient_id/send_outs/:id(.:format)      send_outs#show
#                                     PUT    /accounts/:account_id/recipients/:recipient_id/send_outs/:id(.:format)      send_outs#update
#                                     DELETE /accounts/:account_id/recipients/:recipient_id/send_outs/:id(.:format)      send_outs#destroy
#                  account_recipients GET    /accounts/:account_id/recipients(.:format)                                  recipients#index
#                                     POST   /accounts/:account_id/recipients(.:format)                                  recipients#create
#               new_account_recipient GET    /accounts/:account_id/recipients/new(.:format)                              recipients#new
#              edit_account_recipient GET    /accounts/:account_id/recipients/:id/edit(.:format)                         recipients#edit
#                   account_recipient GET    /accounts/:account_id/recipients/:id(.:format)                              recipients#show
#                                     PUT    /accounts/:account_id/recipients/:id(.:format)                              recipients#update
#                                     DELETE /accounts/:account_id/recipients/:id(.:format)                              recipients#destroy
#                      account_assets POST   /accounts/:account_id/assets(.:format)                                      assets#create

app/models/recipient.rb
class Recipient < ActiveRecord::Base

  SEARCH_COLUMNS = %w(email first_name last_name)

  belongs_to :account

  attr_accessible :gender, :first_name, :last_name, :email
  attr_accessible :account, :state, :gender, :first_name, :last_name, :email, :as => :test

  has_many :newsletters, :through => :account
  has_many :live_send_outs

  scope :greater_than, lambda { |recipient_id|  {:conditions => [ "recipients.id > ?", recipient_id ] } }
  scope :search, lambda { |search| search.blank? ? {} : {:conditions => SEARCH_COLUMNS.map { |column| "#{column} LIKE '%#{search}%'" }.join(' OR ') } }
  scope :confirmed, :conditions => { :state => :confirmed}

  validates :account_id, :presence => true
  validates :email, :presence => true, :uniqueness => {:scope => :account_id}, :email_format => true
  validates :confirm_code, :presence => true, :uniqueness => true, :on => :create

  StateMachine::Machine.ignore_method_conflicts = true #to enable #delete
  state_machine :initial => :pending do
    event :pending do
      transition :pending => :pending
      transition :deleted => :pending
    end

    event :confirm do
      transition :pending => :confirmed
      transition :confirmed => :confirmed
      transition :deleted => :confirmed
    end

    event :disable do
      transition any => :disabled
    end

    event :delete do
      transition any => :deleted
    end
  end

  def self.find_or_build_by(attrs)
    where(attrs).first || new(attrs)
  end

  alias_method :force_destroy, :destroy
  def destroy
    self.delete!
    self
  end

  def update_stats!
    self.deliveries_count = live_send_outs.with_states(:finished, :failed, :bounced, :read).count
    self.bounces_count    = live_send_outs.with_state(:bounced).count
    self.fails_count      = live_send_outs.with_state(:failed).count
    self.reads_count      = live_send_outs.with_state(:read).count
    self.save!
  end

  protected
  # in case we generate a duplicate confirm_code, reset code and regenerate a new one
  def run_validations!
    super.tap do
      if errors[:confirm_code].present?
        self.confirm_code = SecureRandom.hex(8)
        return valid? #re-run validation
      end
    end
  end

  #temporary will soon be gone
  def move_bounce_to_send_outs
    self.bounces.split("\n").each do |bounce|
      begin
        if ids = bounce.scan(/ma-(\d+)-(\d+)/).first
          account_id, newsletter_id = ids
          LiveSendOut.create!(:newsletter_id => newsletter_id, :state => 'bounced', :error_message => bounce, :recipient_id => self.id, :email => self.email)
        end
      rescue => e
        puts e.message
      end
    end
  end
end

# == Schema Information
#
# Table name: recipients
#
#  id               :integer(4)      not null, primary key
#  gender           :string(255)
#  first_name       :string(255)
#  last_name        :string(255)
#  email            :string(255)
#  deliveries_count :integer(4)      default(0), not null
#  bounces_count    :integer(4)      default(0), not null
#  account_id       :integer(4)
#  created_at       :datetime
#  updated_at       :datetime
#  fails_count      :integer(4)      default(0), not null
#  confirm_code     :string(255)
#  state            :string(255)     default("pending")
#  reads_count      :integer(4)      default(0), not null
#

#  updated_at       :datetime

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationNupsController
  before_filter :load_account

  respond_to :html, :xls

  def index
    @recipients = @account.recipients.search(params[:search])

    unless params[:format] == 'xls'
      @recipients = @recipients.with_states(:confirmed).order(params[:order] || :id).page(params[:page]).per(50)
    end
    if request.xhr?
      render :partial => 'recipients'
    else
      respond_with @recipients
    end
  end

  def show
    @recipient = @account.recipients.find(params[:id])
  end

  def new
    render :layout => !request.xhr?
  end

  def create
    @valid_recipients = []
    @invalid_recipients = split_emails(params[:emails]).map do |email|
      recipient = @account.recipients.find_or_build_by(:email => email)
      if recipient.save && recipient.confirm!
        @valid_recipients << recipient
        nil
      else
        recipient
      end
    end.compact

    if request.xhr?
      render :json => {:valid => @valid_recipients.map(&:email), :invalid => @invalid_recipients.map(&:email)}
    else
      render :new, :layout => false
    end
  end

  def update
    @recipient = @account.recipients.find(params[:id])
    @recipient.update_attributes(params[:recipient])

    if request.xhr?
      render :json => @recipient
    else
      redirect_to account_recipients_url(@account)
    end
  end

  def delete
    render :layout => !request.xhr?
  end

  def multiple_destroy
    valids  = []
    invalids = split_emails(params[:emails]).delete_if do |email|
      if recipient = @account.recipients.find_by_email(email)
        recipient.destroy unless params[:delete].blank?
        valids << email
        true
      end
    end

    if request.xhr?
      render :json => {:valid => valids, :invalid => invalids, :delete => params[:delete]}
    else
      redirect_to account_recipients_path(@account)
    end
  end

  def destroy
    @recipient = @account.recipients.find(params[:id])
    @recipient.destroy

    if request.xhr?
      render :json => @recipient.to_json(:only => [:id])
    else
      redirect_to account_recipients_path(@account)
    end
  end

  private
  def split_emails(emails)  #split by \n or , or ;
    return [] unless emails
    emails.delete("\"' ").split(/[\n,;]/).delete_if(&:blank?).map(&:strip).uniq
  end
end

app/helpers/recipients_helper.rb
module RecipientsHelper
end

app/views/recipients/_recipient.html.haml
%tr{:id => "recipient-#{recipient.id}", :class => recipient.state, :"data-recipient-path" => account_recipient_path(recipient.account, recipient)}
  %td.state= recipient.state

  %td.show.gender= recipient.gender
  %td.edit.gender= select_tag "recipient[#{recipient.id}][gender]", options_for_select(['', 'Herr', 'Frau'], recipient.gender)

  %td.show.first-name= recipient.first_name
  %td.edit.first-name= text_field_tag "recipient[#{recipient.id}][first_name]", recipient.first_name

  %td.show.last-name= recipient.last_name
  %td.edit.last-name= text_field_tag "recipient[#{recipient.id}][last_name]", recipient.last_name

  %td.show.email= recipient.email
  %td.edit.email= text_field_tag "recipient[#{recipient.id}][email]", recipient.email

  %td.stats
    = recipient.deliveries_count
    \-
    = recipient.reads_count
    \-
    = recipient.bounces_count

  %td.show.menu
    %a.icon.show{:href => account_recipient_send_outs_path(recipient.account, recipient), :rel => "#overlay"}
      %span=t('ctrl.show')
    %a.icon.edit{:href => '#', :onclick => "$(this).closest('tr').toggleClass('edit');"}
      %span= t('ctrl.edit')
    - url = account_recipient_path(recipient.account, recipient)
    %a.icon.delete{:href => url, 'data-method' => 'delete', 'data-confirm' => t('recipients.confirm.delete'), 'data-remote' => 'true', 'data-type' => 'json'}
      %span= t('ctrl.delete')
  %td.edit.menu
    %a.icon.save{:href => '#'}
      %span= t('ctrl.save')
    %a.icon.cancel{:href => '#', :onclick => "$(this).closest('tr').toggleClass('edit');"}
      %span= t('ctrl.cancel')

app/views/recipients/_recipients.html.haml
- if @recipients.count > 0
  %tr.paginate
    %td{colspan:7, align:"center"}= paginate @recipients, :remote => true

  = render @recipients

  %tr.paginate
    %td{colspan:7, align:"center"}= paginate @recipients, :remote => true

app/views/recipients/delete.html.haml
#recipients.form
  = form_tag multiple_destroy_account_recipients_path(@account), :method => :delete, :remote => true, :class => "destroy" do
    %table.content{:style => "width: 700px, height: 100%"}
      %thead
        %tr
          %th{:align => 'center'}
            %h2= t('.title')

      %tr
        %td
          %ul.result
            %li.valid
              %strong= t('.valid_recipients') + ':'
              %ul
                - Array(@valid_recipients).each do |recipient|
                  %li= recipient.email
              = submit_tag t('.ctrl.valid_delete'), :name => :delete, :confirm => t('.ctrl.confirm_delete'), :class => "confirm"
            %li.invalid
              %strong= t('.invalid_recipients') + ':'
              %ul
                - Array(@invalid_recipients).each do |recipient|
                  %li= recipient.email + " (#{recipient.errors.full_messages.join(', ')})"
          .input
            = t('.explanation')

            = text_area_tag :emails, params[:emails], {:cols => 90, :rows => 25}

            = submit_tag t('.ctrl.check'), :class => "check"

app/views/recipients/index.html.haml
#recipients.index
  %h2= t 'recipients.title', :account_name =>  @account.name, :count => @recipients.total_count

  = form_tag account_recipients_path(@account), :method => :get, :remote => true, :class => 'search' do
    = text_field_tag :search, params[:search], :size => 40, :type => 'search', :placeholder => 'Suche'
    = submit_tag t('ctrl.search')

  .right
    %a.new.button{href:new_account_recipient_path(@account), rel:'#overlay'}
      %span= t('recipients.menu.import')
    %a.button{href:delete_account_recipients_path(@account), rel:'#overlay'}
      %span= t('recipients.menu.delete')
    %a.button{href:account_recipients_path(@account, :format => :xls), style:"width:120px"}
      %span= t('recipients.menu.export_xls')

  = form_tag account_recipients_path(@account), :method => :put, :remote => true, :class => 'recipients' do
    %table.content.zebra
      %thead
        %tr
          %th.state
            %a{:href => account_recipients_path(@account, :order => :state), :data => {:remote => true}}
              = Recipient.human_attribute_name(:state)
          %th.gender
            %a{:href => account_recipients_path(@account, :order => :gender), :data => {:remote => true}}
              = Recipient.human_attribute_name(:gender)
          %th.first_name
            %a{:href => account_recipients_path(@account, :order => :first_name), :data => {:remote => true}}
              = Recipient.human_attribute_name(:first_name)
          %th.last_name
            %a{:href => account_recipients_path(@account, :order => :last_name), :data => {:remote => true}}
              = Recipient.human_attribute_name(:last_name)
          %th.email
            %a{:href => account_recipients_path(@account, :order => :email), :data => {:remote => true}}
              = Recipient.human_attribute_name(:email)
          %th.stats
            %a{:href => account_recipients_path(@account, :order => :deliveries_count),
               :title => Recipient.human_attribute_name(:deliveries_count),
               :data => {:remote => true} }
              V
            \/
            %a{:href => account_recipients_path(@account, :order => :reads_count),
               :title => Recipient.human_attribute_name(:reads_count),
               :data => {:remote => true}}
              G
            \/
            %a{:href => account_recipients_path(@account, :order => :bounces_count),
               :title => Recipient.human_attribute_name(:bounces_count),
               :data => {:remote => true}}
              B
          %th.menu= t('newsletters.menu')

      %tbody
        = render 'recipients'

      %tfoot
        %tr
          %td{colspan:7}
            = t('recipients.nothing')

app/views/recipients/new.html.haml
#recipients.form
  = form_tag account_recipients_path(@account), :method => :post, :remote => true, :class => "new" do
    %table.content{:style => "width: 700px, height: 100%"}
      %thead
        %tr
          %th{:align => 'center'}
            %h2= t('.title')

      %tr
        %td
          %ul.result
            %li.valid
              %strong= t('.valid_recipients') + ':'
              %ul
                - Array(@valid_recipients).each do |recipient|
                  %li= recipient.email
            %li.invalid
              %strong= t('.invalid_recipients') + ':'
              %ul
                - Array(@invalid_recipients).each do |recipient|
                  %li= recipient.email + " (#{recipient.errors.full_messages.join(', ')})"
          .input
            = t('.explanation')

            = text_area_tag :emails, params[:emails], {:cols => 90, :rows => 25}

            = submit_tag t('.ctrl.valid_import')